### ISSUE TITLE
Gagal enkripsi pada lebih dari satu sender device

### ISSUE THREAD

**Issue by zetbaitsu** [ridon/ngobrel#10]
Jika ada pengirim memiliki 2 atau lebih device sebelumnya maka penerima tidak bisa membalas pesan tersebut. Misalnya ada 2 Alice dan 2 Bob. Alice pertama mengirim pesan, maka Bob 2 bisa mendekripsi pesan tersebut, tetapi Bob 2 tidak bisa membalas pesan tersebut, karena ketika dia melakukan enkripsi, dia mendapat galat ```java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] id.ridon.ngobrel.core.Key.raw()' on a null object reference
at id.ridon.ngobrel.core.Ratchet.encrypt(Ratchet.java:219)```. Berikut test nya https://github.com/zetbaitsu/ngobrel/blob/master/android/core/src/androidTest/java/id/ridon/ngobrel/core/SesameConversationInstrumentedTest.java#L330

<p align="center"><br/><img src="https://d1edrlpyc25xu0.cloudfront.net/kiwari-prod/image/upload/ySX4_RYLBq/1522906545-Screen+Shot+2018-04-05+at+12.35.06.png" /><br/></p>

**Comment by mdamt** [comment]
Merged
