### ISSUE TITLE
Gagal dekripsi pada lebih dari 1 pesan awal

### ISSUE THREAD

**Issue by zetbaitsu** [ridon/ngobrel#8]
Saya coba pakai object SesameConversation yang sama untuk tiap kali encrypt data, nah ini kalau si pengirim pertama langsung mengirimkan lebih dari satu pesan sebelum lawan bicaranya membalas, dapat error ```java.security.InvalidKeyException```, seperti yang terjadi pada test berikut https://github.com/zetbaitsu/ngobrel/blob/java/android/core/src/androidTest/java/id/ridon/ngobrel/core/SesameConversationInstrumentedTest.java#L167

<p align="center"><br/><img src="https://d1edrlpyc25xu0.cloudfront.net/kiwari-prod/image/upload/RVPXaZ4Emr/1522043663-Screen+Shot+2018-03-26+at+10.38.14.png" /><br/></p>

Jadi kalau Alice nya mengirim 2 pesan langsung ke Bob untuk pertama kali, pesan yg ke 2 tidak bisa di decrypt oleh Bob, tapi kalau Alice mengirim 1 pesan kemudian Bob membalas, setelah itu semuanya berjalan normal, Alice bisa mengirim lebih dari 1 pesan ke Bob setelah itu.

**Comment by mdamt** [comment]
Fixed in e823415f52312a63fb4401ab220edf3d4c8094da
